### ISSUE TITLE
Test Run Questions and Issues

### ISSUE THREAD

**Issue by EMCP** [JRGEMCP/MAHRIO-HEADER#10]
_Authenticated User_ 

What does dashboard mean? this term should say home instead

* Account Dropdown

* Remove password , should be called “settings” ?
* Need to wire up notifications , decide where in database those are stored for a user
* Instead of `MainPage`, should say.. `Mahr.io Home` ?
* Should just say log out, not logout and logout all devices

**Comment by JesusGuerrero** [comment]
* dashboard is for logged in user (aka student). The student will be able to contribute tutorials and their dashboard shows their active list
* password to settings is fine
* notifications are only setup for new user which has not activated their account. The notifications come from various places of the database but are aggregated and funnel through mahrio-header component
* Okay changing the name
* logout of all devices is enhanced logout... we can hide for now

**Comment by EMCP** [comment]
* I understand dashboard is for users.. but I think the name is odd.. our target market might not quite use that term all the time.  Home would be clearer.

On logout..
* understood if you needed it for debugging

**Comment by EMCP** [comment]
closing since Jesus changed the SPA setup and we need to review again from the beginning
